library(readxl)
library(seastests)
library(ggfortify)
library(fpp2)
library(stargazer)
library(tidyverse)
library(urca)
library(vars)
library(tseries)
Monthly_precip_data <- read_excel("D:/dSE/time series books/project/Monthly precip data.xlsx",
col_types = c("date", "numeric", "numeric",
"numeric"))
view(Monthly_precip_data)
head(Monthly_precip_data)
colnames(Monthly_precip_data)
adf.test(Monthly_precip_data$'HUMIDITY (g/kg)', alternative = "stationary")
adf.test(Monthly_precip_data$'PRECIPITATION (mm/day)', alternative = "stationary")
adf.test(Monthly_precip_data$`TEMPERATURE (C)`, alternative = "stationary")
attach(VAR)
colSums(is.na(Monthly_precip_data))
var_data <- Monthly_precip_data[, c("TEMPERATURE (C)", "HUMIDITY (g/kg)", "PRECIPITATION (mm/day)")]
estim <- VAR(var_data, p=4, type = 'none')
summary(estim)
stargazer(estim[['varresult']], type = 'text' )
roots(estim, modulus = TRUE)
names(estim$varresult)
grancausat <- causality(estim, cause = "TEMPERATURE..C.")
grancausah <- causality(estim, cause = "HUMIDITY..g.kg.")
grancausap <- causality(estim, cause = "PRECIPITATION..mm.day.")
print(grancausat)
print(grancausah)
print(grancausap)
imrsf_temp_hum <- irf(estim, impulse = "TEMPERATURE..C.", response = "HUMIDITY..g.kg.", n.ahead = 10, boot = TRUE, run = 1000, ci =0.95 )
imrsf_temp_prec <- irf(estim, impulse = "TEMPERATURE..C.", response = "PRECIPITATION..mm.day.", n.ahead = 10, boot = TRUE, run = 1000, ci =0.95 )
imrsf_hum_temp <- irf(estim, impulse = "HUMIDITY..g.kg.", response = "TEMPERATURE..C.", n.ahead = 10, boot = TRUE, run = 1000, ci =0.95 )
imrsf_hum_prec <- irf(estim, impulse = "HUMIDITY..g.kg.", response = "PRECIPITATION..mm.day.", n.ahead = 10, boot = TRUE, run = 1000, ci =0.95 )
imrsf_prec_temp <- irf(estim, impulse = "PRECIPITATION..mm.day.", response = "TEMPERATURE..C.", n.ahead = 10, boot = TRUE, run = 1000, ci =0.95 )
imrsf_prec_hum <- irf(estim, impulse = "PRECIPITATION..mm.day.", response = "HUMIDITY..g.kg.", n.ahead = 10, boot = TRUE, run = 1000, ci =0.95 )
plot(imrsf_temp_prec)
plot(imrsf_temp_hum)
plot(imrsf_hum_prec)
plot(imrsf_hum_temp)
plot(imrsf_prec_temp)
plot(imrsf_prec_hum)
Fevd <- fevd(estim, n.ahead = 10)
Plot(Fevd)
